$ANSIBLE_VAULT;1.1;AES256
38393130643638626233336431303338626330613465313939326230346161616432643066353931
3730346636663134633935353635656664386566313933320a333464333364306639323336623735
66316536353131316266303938326665623338393534663638323237613238376563326266303432
6633636438613334380a393231653465356366666132363234393833306239316334353064646537
32646631326464623965616466313162323563383266613539303930373637356339313639653339
66663162663230316430633366613335643138343339363730643633656339646633306435373632
32303934623161303732346161336137623264396337653636653130383334613631393330393330
61393163383134376362633635376461653464366632383865306531646161373665633539323338
35306337303935373238343532393464313336396234656234363339356564366335633831343261
32343232336633393462376163343062643063616331306463366265396365653865626264333635
33336236626637356431613636623966623638326466656366303936636538313665396636333638
34326239316536353665623966336330386261376230623536373561343632396431386664336539
35613331616635376364666132656138636465363833386630666363623763613736
