---
docker_git_revision: master
dspace_version: release-2025.12.002
dspace_solr_version: '8_x'
dspace_postgres_version: '8_x'
dspace_angular_version: release-2025.11.003
gupea_espikning_git_revision: release-2025.12.002
gupea_dflow_import_git_revision: release-2026.01.001
gupea_xslt_uppsok_git_revision: release-2025.10.003
docker_command: ./docker-compose-release-mailpit.sh
angular_host_port: 40030
dspace_host_port: 40031
mailpit_host_port: 40032
gupea_espikning_host_port: 40033
gupea_dflow_import_host_port: 40034
gupea_xslt_uppsok_host_port: 40035
angular_extra_host_port: 40036

dspace_hostname: "{{ app_name }}-dev.ub.gu.se"
angular_hostname: "{{ app_name }}-dev.ub.gu.se"
repository_name: GUPEA-dev

handle_canonical_prefix: 'https://{{ app_name }}-dev.ub.gu.se/handle/'
handle_prefix: '123456789'
