---
DSPACE_POSTGRES_VERSOIN: '{{ dspace_postgres_version }}'
DSPACE_SOLR_VERSION: '{{ dspace_solr_version }}'
DSPACE_VERSION: '{{ dspace_version }}'
DSPACE_ANGULAR_VERSION: '{{ dspace_angular_version }}'
GUPEA_ESPIKNING_GIT_REVISION: '{{ gupea_espikning_git_revision }}'
GUPEA_DFLOW_IMPORT_GIT_REVISION: '{{ gupea_dflow_import_git_revision }}'
GUPEA_XSLT_UPPSOK_GIT_REVISION: '{{ gupea_xslt_uppsok_git_revision }}'
DSPACE_HOST_PORT: '127.0.0.1:{{ dspace_host_port }}'
ANGULAR_HOST_PORT: '127.0.0.1:{{ angular_host_port }}'
MAILPIT_HOST_PORT: '127.0.0.1:{{ mailpit_host_port }}'
GUPEA_ESPIKNING_HOST_PORT: '127.0.0.1:{{ gupea_espikning_host_port }}'
GUPEA_DFLOW_IMPORT_HOST_PORT: '127.0.0.1:{{ gupea_dflow_import_host_port }}'
GUPEA_XSLT_UPPSOK_HOST_PORT: '127.0.0.1:{{ gupea_xslt_uppsok_host_port }}'
ANGULAR_EXTRA_HOST_PORT: '127.0.0.1:{{ angular_extra_host_port }}'

DSPACE_PUBLIC_HOST: '{{ dspace_hostname }}'
ANGULAR_PUBLIC_HOST: '{{ angular_hostname }}'
REPOSITORY_NAME: '{{ repository_name }}'

HANDLE_CANONICAL_PREFIX: '{{ handle_canonical_prefix }}'
HANDLE_PREFIX: '{{ handle_prefix }}'

POSTGRES_DATA_HOST_DIR: '{{ data_dirs.postgres.path }}'
SOLR_DATA_HOST_DIR: '{{ data_dirs.solr.path }}'
DSPACE_ASSET_STORE_HOST_DIR: '{{ data_dirs.dspace_asset_store.path }}'
DSPACE_LOGS_HOST_DIR: '{{ data_dirs.dspace_logs.path }}'
DSPACE_SITEMAPS_HOST_DIR: '{{ data_dirs.dspace_sitemaps.path }}'
GUPEA_DFLOW_IMPORT_DATA_HOST_DIR: '{{ data_dirs.gupea_dflow_import.path }}'
DSPACE_API_BASE_URL: 'https://{{ dspace_hostname }}/server/api'
